# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 04:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.IntegerField()),
                ('pokemon_name', models.CharField(max_length=100)),
                ('pokemon_number', models.IntegerField()),
                ('raid_level', models.IntegerField()),
                ('gym_name', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('private_channel', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaidMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=64)),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.Raid')),
            ],
        ),
        migrations.CreateModel(
            name='RaidParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=255)),
                ('party_size', models.IntegerField(default=1)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('attending', models.BooleanField(default=True)),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.Raid')),
            ],
        ),
    ]
