# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_auto_20170907_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='hatch_time',
            field=models.DateTimeField(null=True),
        ),
    ]
