# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_raidzone_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raidzone',
            old_name='server',
            new_name='guild',
        ),
    ]
