# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0009_auto_20170914_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='private_channel',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='raidmessage',
            name='channel',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='raidmessage',
            name='message',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='raidparticipant',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='raidzone',
            name='destination',
            field=models.BigIntegerField(),
        ),
    ]
