# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0010_auto_20170915_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botonlychannel',
            name='channel',
            field=models.BigIntegerField(),
        ),
    ]
