# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0011_auto_20170916_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidzone',
            name='radius',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=4),
        ),
    ]
