# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0012_auto_20170916_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidzone',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
