# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0014_guildconfig_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildconfig',
            name='alarm_source',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guildconfig',
            name='command',
            field=models.CharField(default='!', max_length=1),
        ),
        migrations.AlterField(
            model_name='guildconfig',
            name='rsvp_channel',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guildconfig',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
