# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0015_auto_20170919_2350'),
        ('orm', '0013_auto_20170920_2216'),
    ]

    operations = [
    ]
