# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0014_raidzone_name'),
        ('orm', '0016_merge_20170921_1844'),
    ]

    operations = [
    ]
