# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0018_guildconfig_raid_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
