# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0019_raid_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildconfig',
            name='ex_raid_channel',
            field=models.BigIntegerField(null=True),
        ),
    ]
