# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0020_guildconfig_ex_raid_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='reporting_user',
            field=models.BigIntegerField(null=True),
        ),
    ]
