# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0021_raid_reporting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildconfig',
            name='ex_duration',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='guildconfig',
            name='raid_duration',
            field=models.IntegerField(default=45),
        ),
    ]
