# Generated by Django 2.2 on 2020-08-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0022_auto_20180922_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='is_mega',
            field=models.BooleanField(default=False),
        ),
    ]
